Repository JinCheng26/react-Wallet-connect-frontend-for-za, pull requests merged in 2023-03, with the labels that each got.

#1 install module
  .gitignore
  package-lock.json
  package.json
  tailwind.config.js
  tsconfig.json
Labels: question

#4 add assets
  src/assets/icons.tsx
  src/assets/icons/alarm.svg
  src/assets/icons/apple.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/arrowForward.svg
  src/assets/icons/calendar.svg
  src/assets/icons/checked.svg
  src/assets/icons/close.svg
  src/assets/icons/contacts.svg
  src/assets/icons/contracts.svg
  src/assets/icons/dashboard.svg
  src/assets/icons/double-check.svg
  src/assets/icons/download.svg
  src/assets/icons/email.svg
  src/assets/icons/facebook.svg
  src/assets/icons/google.svg
  src/assets/icons/horizontalSeeMore.svg
  src/assets/icons/info.svg
  src/assets/icons/instagram.svg
  src/assets/icons/lamp.svg
  src/assets/icons/line.svg
  src/assets/icons/linkedin.svg
  src/assets/icons/loading.svg
  src/assets/icons/logo.svg
  src/assets/icons/main-logo.svg
  src/assets/icons/metamask.svg
  src/assets/icons/onlineState.svg
  src/assets/icons/option.svg
  src/assets/icons/pencil.svg
  src/assets/icons/phone.svg
  src/assets/icons/plus.svg
  src/assets/icons/search.svg
  src/assets/icons/settings.svg
  src/assets/icons/shortline.svg
  src/assets/icons/sort.svg
  src/assets/icons/telegram.svg
  src/assets/icons/twitter.svg
  src/assets/icons/unChecked.svg
  src/assets/icons/userAvatar.svg
  src/assets/icons/vertialSeeMore.svg
  src/assets/icons/welcome.svg
  src/assets/logo.svg
Labels: documentation, enhancement

#5 add layouts folder
  src/layouts/MainLayout.tsx
  src/layouts/Sidebar.tsx
Labels: infra

#6 feat :style and redux
  src/store/index.tsx
  src/styles/_normalize.scss
  src/styles/_variables.scss
  src/styles/index.scss
  src/styles/layout.scss
  src/styles/layouts/sidebar.scss
  src/styles/utilities.scss
Labels: infra

#10 add components and routers
  src/components/AuthenticatedRoutes.tsx
  src/components/Routes.tsx
  src/components/buttons/HeaderButton.tsx
  src/components/buttons/index.ts
  src/components/common/BaseInput.tsx
  src/components/common/CheckBox.tsx
  src/components/common/ConfirmDialog.scss
  src/components/common/ConfirmDialog.tsx
  src/components/common/ContractCard.tsx
  src/components/common/ListWithSwitch.tsx
  src/components/common/Search.tsx
  src/components/common/StatisticsCards.tsx
  src/components/common/TransactionCard.tsx
  src/components/common/TransactionItem.tsx
  src/components/common/UserItem.tsx
  src/components/common/calendar/calendar.scss
  src/components/common/calendar/calendar.tsx
Labels: infra
